// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.5
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_cube(i,f,a){
	var c=jQuery;var d=c("ul",a);
	var b={
			position:"absolute",
			left:0,
			top:0,
			width:"100%",
			height:"100%"
	};
	var h={
			domPrefixes:" Webkit Moz ms O Khtml".split(" "),
			testDom:function(k){
				var j=this.domPrefixes.length;
				while(j--){
					if(typeof document.body.style[this.domPrefixes[j]+k]!=="undefined"){
						return true
					}
				}
				return false
			},
			cssTransitions:function(){return this.testDom("Transition")},
			cssTransforms3d:function(){
				var k=(typeof document.body.style.perspectiveProperty!=="undefined")||this.testDom("Perspective");
				if(k){
					var m=document.createElement("div"),
					j=document.createElement("style"),
					l="Test3d"+Math.round(Math.random()*99999);
					j.textContent="@media (-webkit-transform-3d){#"+l+"{height:3px}}";
					document.getElementsByTagName("head")[0].appendChild(j);
					m.id=l;document.body.appendChild(m);
					k=m.offsetHeight===3;
					j.parentNode.removeChild(j);
					m.parentNode.removeChild(m)}return k
					}
			};
	function g(j,k,m,l){
		return"inset "+(-l*j*1.2/90)+"px "+(m*k*1.2/90)+"px "+(j+k)/20+"px rgba("+((m<l)?"0,0,0,.6":(m>l)?"255,255,255,0.8":"0,0,0,.0")+")"}var e;
		this.go=function(q,n){
			function k(I,x,y,v,u,G,H,E,D){
				I.parent().css("perspective",1000);
				var C=I.width(),
				A=I.height();
				var F=c(I.children().get(1));
				F.css({
					transform:"translateZ("+x+"px)",
					backfaceVisibility:"hidden",
					"box-shadow":g(C,A,0,0)
				});
				var z=c(I.children().get(0));
				z.css({opacity:1,transform:"translateY("+v+"px) translateX("+y+"px) rotateY("+G+"deg) rotateX("+u+"deg)",
					backfaceVisibility:"hidden","box-shadow":g(C,A,u,G)});
				I.css({transform:"translateZ(-"+x+"px)",
					transformStyle:"preserve-3d"});
				var B=setTimeout(function(){
					var w="all "+i.duration+"ms cubic-bezier(0.645, 0.045, 0.355, 1.000)";
					I.css({
						transition:w,
						transform:"translateZ(-"+x+"px) rotateX("+H+"deg) rotateY("+E+"deg)"});
					F.css({
						transition:w,
						"box-shadow":g(C,A,H,E)});
					z.css({transition:w,
						"box-shadow":g(C,A,0,0)});
					B=setTimeout(D,i.duration)},20);
				return{
					stop:function(){
						clearTimeout(B);
						D()
						}
				}
			}
			if(h.cssTransitions()&&h.cssTransforms3d()&&!document.all){
				if(e){
					e.stop()
				}
				var t=c('<div class="ws_effect">').css(b).css({zIndex:8}).appendTo(a.parent());
				c("<div>").css(b).appendTo(t).css({"background-image":"url("+f.get(q).src+")","background-size":"cover"});
				c("<div>").css(b).appendTo(t).css({"background-image":"url("+f.get(n).src+")","background-size":"cover"});
				d.hide();
				var s=a.width(),
				o=a.height(),
				m={
					left:[s/2,s/2,0,0,90,0,-90],
					right:[s/2,-s/2,0,0,-90,0,90],
					down:[o/2,0,-o/2,90,0,-90,0],
					up:[o/2,0,o/2,-90,0,90,0]
				}[i.direction||["left","right","down","up"][Math.floor(Math.random()*4)]];
				e=new k(t,m[0],m[1],m[2],m[3],m[4],m[5],m[6],function(){
					d.css({left:-q+"00%"}).show();
					t.remove();e=0})
			}else{
				var j=c("<div></div>").css({position:"absolute",display:"none","z-index":2,width:"100%",height:"100%"}).appendTo(a);
				j.stop(1,1);
				var l=(!!((q-n+1)%f.length)^i.revers?"left":"right");
				var r=c(f[n]).clone().css({position:"absolute",left:"0%",right:"auto",top:0,width:"100%",height:"100%",}).appendTo(j).css(l,0);
				var p=c(f[q]).clone().css({position:"absolute",left:"100%",right:"auto",top:0,width:"0%",height:"100%",}).appendTo(j).show();
				j.css({left:"auto",right:"auto",top:0}).css(l,0).show();
				d.hide();
				p.animate({width:"100%",left:0},i.duration,"easeInOutExpo",function(){c(this).remove()});
				r.animate({width:0},i.duration,"easeInOutExpo",function(){d.css({left:-q+"00%"}).show();j.remove()})
			}
			return q
		}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.5
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery(".wowslider-container1").wowSlider({
	effect:"cube",	prev:"",	next:"",	duration:20*100,	delay:0*100,	width:341,	height:218,
	autoPlay:true,	playPause:false,	stopOnHover:false,	loop:false,	bullets:0,	caption:false,	captionEffect:"slide",
	controls:false,	onBeforeStep:0,	images:0,	direction:"left"});

//i.direction||["left","right","down","up"