/*
 * jQuery UI 1.8.2
 *
 * Copyright (c) 2010 AUTHORS.txt (http://jqueryui.com/about)
 * Dual licensed under the MIT (MIT-LICENSE.txt)
 * and GPL (GPL-LICENSE.txt) licenses.
 *
 * http://docs.jquery.com/UI
 */
(function(a){a.ui=a.ui||{};if(a.ui.version){return;}a.extend(a.ui,{version:"1.8.2",plugin:{add:function(c,d,f){var e=a.ui[c].prototype;for(var b in f){e.plugins[b]=e.plugins[b]||[];e.plugins[b].push([d,f[b]]);}},call:function(d,e,b){var f=d.plugins[e];if(!f||!d.element[0].parentNode){return;}for(var c=0;c<f.length;c++){if(d.options[f[c][0]]){f[c][1].apply(d.element,b);}}}},contains:function(c,d){return document.compareDocumentPosition?c.compareDocumentPosition(d)&16:c!==d&&c.contains(d);},hasScroll:function(c,b){if(a(c).css("overflow")=="hidden"){return false;}var e=(b&&b=="left")?"scrollLeft":"scrollTop",d=false;if(c[e]>0){return true;}c[e]=1;d=(c[e]>0);c[e]=0;return d;},isOverAxis:function(d,b,c){return(d>b)&&(d<(b+c));},isOver:function(g,f,d,c,b,e){return a.ui.isOverAxis(g,d,b)&&a.ui.isOverAxis(f,c,e);},keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});a.fn.extend({_focus:a.fn.focus,focus:function(b,c){return typeof b==="number"?this.each(function(){var d=this;setTimeout(function(){a(d).focus();(c&&c.call(d));},b);}):this._focus.apply(this,arguments);},enableSelection:function(){return this.attr("unselectable","off").css("MozUserSelect","");},disableSelection:function(){return this.attr("unselectable","on").css("MozUserSelect","none");},scrollParent:function(){var b;if((a.browser.msie&&(/(static|relative)/).test(this.css("position")))||(/absolute/).test(this.css("position"))){b=this.parents().filter(function(){return(/(relative|absolute|fixed)/).test(a.curCSS(this,"position",1))&&(/(auto|scroll)/).test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1));}).eq(0);}else{b=this.parents().filter(function(){return(/(auto|scroll)/).test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1));}).eq(0);}return(/fixed/).test(this.css("position"))||!b.length?a(document):b;},zIndex:function(e){if(e!==undefined){return this.css("zIndex",e);}if(this.length){var b=a(this[0]),c,d;while(b.length&&b[0]!==document){c=b.css("position");if(c=="absolute"||c=="relative"||c=="fixed"){d=parseInt(b.css("zIndex"));if(!isNaN(d)&&d!=0){return d;}}b=b.parent();}}return 0;}});a.extend(a.expr[":"],{data:function(b,c,d){return !!a.data(b,d[3]);},focusable:function(b){var c=b.nodeName.toLowerCase(),d=a.attr(b,"tabindex");return(/input|select|textarea|button|object/.test(c)?!b.disabled:"a"==c||"area"==c?b.href||!isNaN(d):!isNaN(d))&&!a(b)["area"==c?"parents":"closest"](":hidden").length;},tabbable:function(b){var c=a.attr(b,"tabindex");return(isNaN(c)||c>=0)&&a(b).is(":focusable");}});})(jQuery);