package com.gaopin.entity;

// Generated Sep 22, 2015 3:45:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrImagegallerySub generated by hbm2java
 */
@Entity
@Table(name = "fr_imagegallery_sub", catalog = "gaopin_images")
public class FrImagegallerySub implements java.io.Serializable {

	private Integer id;
	private Integer imagesetId;
	private String name;
	private Integer status;
	private String info;
	private Integer num;
	private Integer seq;
	private String src;
	private String imgList;
	private String style;
	private Date createTime;
	private Date updateTime;
	private String imageSetSrc;

	public FrImagegallerySub() {
	}

	public FrImagegallerySub(Integer imagesetId, String name, Integer status,
			String info, Integer num, Integer seq, String src, String imgList,
			String style, Date createTime, Date updateTime, String imageSetSrc) {
		this.imagesetId = imagesetId;
		this.name = name;
		this.status = status;
		this.info = info;
		this.num = num;
		this.seq = seq;
		this.src = src;
		this.imgList = imgList;
		this.style = style;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.imageSetSrc = imageSetSrc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "imageset_id")
	public Integer getImagesetId() {
		return this.imagesetId;
	}

	public void setImagesetId(Integer imagesetId) {
		this.imagesetId = imagesetId;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "info", length = 256)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "num")
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "src", length = 256)
	public String getSrc() {
		return this.src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	@Column(name = "img_list", length = 16777215)
	public String getImgList() {
		return this.imgList;
	}

	public void setImgList(String imgList) {
		this.imgList = imgList;
	}

	@Column(name = "style", length = 100)
	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "image_set_src", length = 768)
	public String getImageSetSrc() {
		return this.imageSetSrc;
	}

	public void setImageSetSrc(String imageSetSrc) {
		this.imageSetSrc = imageSetSrc;
	}

}
