package com.gaopin.entity;

// Generated Jun 3, 2015 11:19:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrMotionInfo generated by hbm2java
 */
@Entity
@Table(name = "fr_motion_info", catalog = "gaopin_images")
public class FrMotionInfo implements java.io.Serializable {

	private long id;
	private String gaopinId;
	private Byte storageId;
	private String title;
	private String caption;
	private Integer photographerId;
	private Integer collectionId;
	private Integer categoryId;
	private Date shotDate;
	private String shotDateDes;
	private Byte status;
	private Byte modeStatus;
	private Byte propertyStatus;
	private String location;
	private String creditLine;
	private Byte licenseType;
	private String maxSize;
	private Boolean isInCd;
	private Boolean isInMotionSet;
	private Boolean isInMotionGroup;
	private Date publishDate;
	private String restrictionIds;
	private Integer sortId;
	private Date createTime;
	private Date updateTime;
	private Integer pricing;
	private Float duration;
	private String mediaType;
	private String fps;
	private String codec;

	public FrMotionInfo() {
	}

	public FrMotionInfo(long id) {
		this.id = id;
	}

	public FrMotionInfo(long id, String gaopinId, Byte storageId, String title,
			String caption, Integer photographerId, Integer collectionId,
			Integer categoryId, Date shotDate, String shotDateDes, Byte status,
			Byte modeStatus, Byte propertyStatus, String location,
			String creditLine, Byte licenseType, String maxSize,
			Boolean isInCd, Boolean isInMotionSet, Boolean isInMotionGroup,
			Date publishDate, String restrictionIds, Integer sortId,
			Date createTime, Date updateTime, Integer pricing, Float duration,
			String mediaType, String fps, String codec) {
		this.id = id;
		this.gaopinId = gaopinId;
		this.storageId = storageId;
		this.title = title;
		this.caption = caption;
		this.photographerId = photographerId;
		this.collectionId = collectionId;
		this.categoryId = categoryId;
		this.shotDate = shotDate;
		this.shotDateDes = shotDateDes;
		this.status = status;
		this.modeStatus = modeStatus;
		this.propertyStatus = propertyStatus;
		this.location = location;
		this.creditLine = creditLine;
		this.licenseType = licenseType;
		this.maxSize = maxSize;
		this.isInCd = isInCd;
		this.isInMotionSet = isInMotionSet;
		this.isInMotionGroup = isInMotionGroup;
		this.publishDate = publishDate;
		this.restrictionIds = restrictionIds;
		this.sortId = sortId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.pricing = pricing;
		this.duration = duration;
		this.mediaType = mediaType;
		this.fps = fps;
		this.codec = codec;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "gaopin_id", length = 30)
	public String getGaopinId() {
		return this.gaopinId;
	}

	public void setGaopinId(String gaopinId) {
		this.gaopinId = gaopinId;
	}

	@Column(name = "storage_id")
	public Byte getStorageId() {
		return this.storageId;
	}

	public void setStorageId(Byte storageId) {
		this.storageId = storageId;
	}

	@Column(name = "title", length = 300)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "caption", length = 1000)
	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	@Column(name = "photographer_id")
	public Integer getPhotographerId() {
		return this.photographerId;
	}

	public void setPhotographerId(Integer photographerId) {
		this.photographerId = photographerId;
	}

	@Column(name = "collection_id")
	public Integer getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(Integer collectionId) {
		this.collectionId = collectionId;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shot_date", length = 19)
	public Date getShotDate() {
		return this.shotDate;
	}

	public void setShotDate(Date shotDate) {
		this.shotDate = shotDate;
	}

	@Column(name = "shot_date_des", length = 100)
	public String getShotDateDes() {
		return this.shotDateDes;
	}

	public void setShotDateDes(String shotDateDes) {
		this.shotDateDes = shotDateDes;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "mode_status")
	public Byte getModeStatus() {
		return this.modeStatus;
	}

	public void setModeStatus(Byte modeStatus) {
		this.modeStatus = modeStatus;
	}

	@Column(name = "property_status")
	public Byte getPropertyStatus() {
		return this.propertyStatus;
	}

	public void setPropertyStatus(Byte propertyStatus) {
		this.propertyStatus = propertyStatus;
	}

	@Column(name = "location", length = 200)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "credit_line", length = 200)
	public String getCreditLine() {
		return this.creditLine;
	}

	public void setCreditLine(String creditLine) {
		this.creditLine = creditLine;
	}

	@Column(name = "license_type")
	public Byte getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(Byte licenseType) {
		this.licenseType = licenseType;
	}

	@Column(name = "max_size", length = 100)
	public String getMaxSize() {
		return this.maxSize;
	}

	public void setMaxSize(String maxSize) {
		this.maxSize = maxSize;
	}

	@Column(name = "is_in_cd")
	public Boolean getIsInCd() {
		return this.isInCd;
	}

	public void setIsInCd(Boolean isInCd) {
		this.isInCd = isInCd;
	}

	@Column(name = "is_in_motion_set")
	public Boolean getIsInMotionSet() {
		return this.isInMotionSet;
	}

	public void setIsInMotionSet(Boolean isInMotionSet) {
		this.isInMotionSet = isInMotionSet;
	}

	@Column(name = "is_in_motion_group")
	public Boolean getIsInMotionGroup() {
		return this.isInMotionGroup;
	}

	public void setIsInMotionGroup(Boolean isInMotionGroup) {
		this.isInMotionGroup = isInMotionGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publish_date", length = 19)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Column(name = "restriction_ids", length = 200)
	public String getRestrictionIds() {
		return this.restrictionIds;
	}

	public void setRestrictionIds(String restrictionIds) {
		this.restrictionIds = restrictionIds;
	}

	@Column(name = "sort_id")
	public Integer getSortId() {
		return this.sortId;
	}

	public void setSortId(Integer sortId) {
		this.sortId = sortId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "pricing")
	public Integer getPricing() {
		return this.pricing;
	}

	public void setPricing(Integer pricing) {
		this.pricing = pricing;
	}

	@Column(name = "duration", precision = 12, scale = 0)
	public Float getDuration() {
		return this.duration;
	}

	public void setDuration(Float duration) {
		this.duration = duration;
	}

	@Column(name = "media_type", length = 100)
	public String getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

	@Column(name = "fps", length = 10)
	public String getFps() {
		return this.fps;
	}

	public void setFps(String fps) {
		this.fps = fps;
	}

	@Column(name = "codec", length = 100)
	public String getCodec() {
		return this.codec;
	}

	public void setCodec(String codec) {
		this.codec = codec;
	}

}
