package com.gaopin.entity;

// Generated Nov 13, 2015 9:48:02 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LtNonloginUserWin generated by hbm2java
 */
@Entity
@Table(name = "lt_nonlogin_user_win", catalog = "gaopin_images")
public class LtNonloginUserWin implements java.io.Serializable {

	private Integer id;
	private String sessionId;
	private Integer awardId;
	private Integer userId;
	private Integer accept;
	private String keyword;
	private Date createTime;
	private Date acceptTime;
	private Date expiredTime;
	private String userIp;

	public LtNonloginUserWin() {
	}

	public LtNonloginUserWin(String sessionId, Integer awardId, Integer userId,
			Integer accept, String keyword, Date createTime, Date acceptTime,
			Date expiredTime, String userIp) {
		this.sessionId = sessionId;
		this.awardId = awardId;
		this.userId = userId;
		this.accept = accept;
		this.keyword = keyword;
		this.createTime = createTime;
		this.acceptTime = acceptTime;
		this.expiredTime = expiredTime;
		this.userIp = userIp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "session_id", length = 50)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "award_id")
	public Integer getAwardId() {
		return this.awardId;
	}

	public void setAwardId(Integer awardId) {
		this.awardId = awardId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "accept")
	public Integer getAccept() {
		return this.accept;
	}

	public void setAccept(Integer accept) {
		this.accept = accept;
	}

	@Column(name = "keyword", length = 50)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "accept_time", length = 19)
	public Date getAcceptTime() {
		return this.acceptTime;
	}

	public void setAcceptTime(Date acceptTime) {
		this.acceptTime = acceptTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expired_time", length = 19)
	public Date getExpiredTime() {
		return this.expiredTime;
	}

	public void setExpiredTime(Date expiredTime) {
		this.expiredTime = expiredTime;
	}

	@Column(name = "user_ip", length = 50)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
