package com.gaopin.entity;

// Generated Dec 18, 2015 2:32:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TubeSetRel generated by hbm2java
 */
@Entity
@Table(name = "tube_set_rel", uniqueConstraints = @UniqueConstraint(columnNames = {
		"set_id", "image_id" }))
public class TubeSetRel implements java.io.Serializable {

	private Long id;
	private Integer setId;
	private String imageId;
	private String memo;
	private Date createTime;
	private Date updateTime;

	public TubeSetRel() {
	}

	public TubeSetRel(Integer setId, String imageId, String memo,
			Date createTime, Date updateTime) {
		this.setId = setId;
		this.imageId = imageId;
		this.memo = memo;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "set_id")
	public Integer getSetId() {
		return this.setId;
	}

	public void setSetId(Integer setId) {
		this.setId = setId;
	}

	@Column(name = "image_id", length = 50)
	public String getImageId() {
		return this.imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	@Column(name = "memo", length = 1000)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
