package com.gaopin.entity;

// Generated Dec 18, 2015 2:32:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TubeContestVote generated by hbm2java
 */
@Entity
@Table(name = "tube_contest_vote")
public class TubeContestVote implements java.io.Serializable {

	private Integer id;
	private String imageid;
	private String userid;
	private String contestid;
	private String sessionid;
	private Date votetime;

	public TubeContestVote() {
	}

	public TubeContestVote(String imageid) {
		this.imageid = imageid;
	}

	public TubeContestVote(String imageid, String userid, String contestid,
			String sessionid, Date votetime) {
		this.imageid = imageid;
		this.userid = userid;
		this.contestid = contestid;
		this.sessionid = sessionid;
		this.votetime = votetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "imageid", nullable = false, length = 50)
	public String getImageid() {
		return this.imageid;
	}

	public void setImageid(String imageid) {
		this.imageid = imageid;
	}

	@Column(name = "userid", length = 50)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "contestid", length = 10)
	public String getContestid() {
		return this.contestid;
	}

	public void setContestid(String contestid) {
		this.contestid = contestid;
	}

	@Column(name = "sessionid", length = 50)
	public String getSessionid() {
		return this.sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "votetime", length = 19)
	public Date getVotetime() {
		return this.votetime;
	}

	public void setVotetime(Date votetime) {
		this.votetime = votetime;
	}

}
