package com.gaopin.entity;

// Generated Dec 18, 2015 2:32:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TubePReleases generated by hbm2java
 */
@Entity
@Table(name = "tube_p_releases")
public class TubePReleases implements java.io.Serializable {

	private Integer id;
	private Integer userid;
	private String useruuid;
	private String filename;
	private String fileid;
	private int status;
	private Date dateupload;

	public TubePReleases() {
	}

	public TubePReleases(int status) {
		this.status = status;
	}

	public TubePReleases(Integer userid, String useruuid, String filename,
			String fileid, int status, Date dateupload) {
		this.userid = userid;
		this.useruuid = useruuid;
		this.filename = filename;
		this.fileid = fileid;
		this.status = status;
		this.dateupload = dateupload;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userid")
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "useruuid", length = 50)
	public String getUseruuid() {
		return this.useruuid;
	}

	public void setUseruuid(String useruuid) {
		this.useruuid = useruuid;
	}

	@Column(name = "filename", length = 50)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "fileid", length = 50)
	public String getFileid() {
		return this.fileid;
	}

	public void setFileid(String fileid) {
		this.fileid = fileid;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateupload", length = 19)
	public Date getDateupload() {
		return this.dateupload;
	}

	public void setDateupload(Date dateupload) {
		this.dateupload = dateupload;
	}

}
