package com.gaopin.entity;

// Generated Dec 18, 2015 2:32:33 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TubeCopyright generated by hbm2java
 */
@Entity
@Table(name = "tube_copyright")
public class TubeCopyright implements java.io.Serializable {

	private Integer id;
	private String copyrightid;
	private String copyrightname;
	private int status;

	public TubeCopyright() {
	}

	public TubeCopyright(String copyrightid, int status) {
		this.copyrightid = copyrightid;
		this.status = status;
	}

	public TubeCopyright(String copyrightid, String copyrightname, int status) {
		this.copyrightid = copyrightid;
		this.copyrightname = copyrightname;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "copyrightid", nullable = false, length = 10)
	public String getCopyrightid() {
		return this.copyrightid;
	}

	public void setCopyrightid(String copyrightid) {
		this.copyrightid = copyrightid;
	}

	@Column(name = "copyrightname", length = 50)
	public String getCopyrightname() {
		return this.copyrightname;
	}

	public void setCopyrightname(String copyrightname) {
		this.copyrightname = copyrightname;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
