package com.gaopin.entity;

// Generated Dec 18, 2015 2:32:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TubeQqLogin generated by hbm2java
 */
@Entity
@Table(name = "tube_qq_login")
public class TubeQqLogin implements java.io.Serializable {

	private Integer id;
	private String openid;
	private String accesstoken;
	private Integer userid;
	private String useruuid;
	private Date createtime;

	public TubeQqLogin() {
	}

	public TubeQqLogin(String openid, String accesstoken, Integer userid,
			String useruuid, Date createtime) {
		this.openid = openid;
		this.accesstoken = accesstoken;
		this.userid = userid;
		this.useruuid = useruuid;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "openid", length = 50)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "accesstoken", length = 50)
	public String getAccesstoken() {
		return this.accesstoken;
	}

	public void setAccesstoken(String accesstoken) {
		this.accesstoken = accesstoken;
	}

	@Column(name = "userid")
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "useruuid", length = 50)
	public String getUseruuid() {
		return this.useruuid;
	}

	public void setUseruuid(String useruuid) {
		this.useruuid = useruuid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
