package com.gaopin.entity;

// Generated Dec 21, 2015 4:42:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TubeUsers generated by hbm2java
 */
@Entity
@Table(name = "tube_users", uniqueConstraints = @UniqueConstraint(columnNames = "userid"))
public class TubeUsers implements java.io.Serializable {

	private Integer id;
	private String userid;
	private int userLevel;
	private String firstname;
	private String lastname;
	private String nickname;
	private String userName;
	private String loginname;
	private String password;
	private String birthday;
	private Integer sex;
	private String email;
	private String mobilenumber;
	private String smsvcode;
	private String emailvcode;
	private Integer emailverified;
	private Integer mobileverified;
	private String wechatid;
	private String weiboid;
	private String qqid;
	private Integer quota;
	private String address;
	private Date createtime;
	private Integer status;
	private Date updatetime;
	private String socialInfo;
	private String deviceInfo;
	private String contactsInfo;
	private String avatarStoreid;
	private String avatar;
	private String coverimageStoreid;
	private String coverimage;
	private String idcardimage;
	private String idcardnumber;
	private String realname;
	private String randomstring;
	private String bankinfo;
	private boolean isactive;
	private String activecode;
	private String alipayaccount;
	private String signature;
	private String regionUser;
	private String cityUser;
	private String selfintro;
	private String registerby;

	public TubeUsers() {
	}

	public TubeUsers(String userid, int userLevel, boolean isactive) {
		this.userid = userid;
		this.userLevel = userLevel;
		this.isactive = isactive;
	}

	public TubeUsers(String userid, int userLevel, String firstname,
			String lastname, String nickname, String userName,
			String loginname, String password, String birthday, Integer sex,
			String email, String mobilenumber, String smsvcode,
			String emailvcode, Integer emailverified, Integer mobileverified,
			String wechatid, String weiboid, String qqid, Integer quota,
			String address, Date createtime, Integer status, Date updatetime,
			String socialInfo, String deviceInfo, String contactsInfo,
			String avatarStoreid, String avatar, String coverimageStoreid,
			String coverimage, String idcardimage, String idcardnumber,
			String realname, String randomstring, String bankinfo,
			boolean isactive, String activecode, String alipayaccount,
			String signature, String regionUser, String cityUser,
			String selfintro, String registerby) {
		this.userid = userid;
		this.userLevel = userLevel;
		this.firstname = firstname;
		this.lastname = lastname;
		this.nickname = nickname;
		this.userName = userName;
		this.loginname = loginname;
		this.password = password;
		this.birthday = birthday;
		this.sex = sex;
		this.email = email;
		this.mobilenumber = mobilenumber;
		this.smsvcode = smsvcode;
		this.emailvcode = emailvcode;
		this.emailverified = emailverified;
		this.mobileverified = mobileverified;
		this.wechatid = wechatid;
		this.weiboid = weiboid;
		this.qqid = qqid;
		this.quota = quota;
		this.address = address;
		this.createtime = createtime;
		this.status = status;
		this.updatetime = updatetime;
		this.socialInfo = socialInfo;
		this.deviceInfo = deviceInfo;
		this.contactsInfo = contactsInfo;
		this.avatarStoreid = avatarStoreid;
		this.avatar = avatar;
		this.coverimageStoreid = coverimageStoreid;
		this.coverimage = coverimage;
		this.idcardimage = idcardimage;
		this.idcardnumber = idcardnumber;
		this.realname = realname;
		this.randomstring = randomstring;
		this.bankinfo = bankinfo;
		this.isactive = isactive;
		this.activecode = activecode;
		this.alipayaccount = alipayaccount;
		this.signature = signature;
		this.regionUser = regionUser;
		this.cityUser = cityUser;
		this.selfintro = selfintro;
		this.registerby = registerby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userid", unique = true, nullable = false, length = 50)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "user_level", nullable = false)
	public int getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(int userLevel) {
		this.userLevel = userLevel;
	}

	@Column(name = "firstname", length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "nickname", length = 50)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "loginname", length = 100)
	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "birthday", length = 100)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobilenumber", length = 20)
	public String getMobilenumber() {
		return this.mobilenumber;
	}

	public void setMobilenumber(String mobilenumber) {
		this.mobilenumber = mobilenumber;
	}

	@Column(name = "smsvcode", length = 10)
	public String getSmsvcode() {
		return this.smsvcode;
	}

	public void setSmsvcode(String smsvcode) {
		this.smsvcode = smsvcode;
	}

	@Column(name = "emailvcode", length = 10)
	public String getEmailvcode() {
		return this.emailvcode;
	}

	public void setEmailvcode(String emailvcode) {
		this.emailvcode = emailvcode;
	}

	@Column(name = "emailverified")
	public Integer getEmailverified() {
		return this.emailverified;
	}

	public void setEmailverified(Integer emailverified) {
		this.emailverified = emailverified;
	}

	@Column(name = "mobileverified")
	public Integer getMobileverified() {
		return this.mobileverified;
	}

	public void setMobileverified(Integer mobileverified) {
		this.mobileverified = mobileverified;
	}

	@Column(name = "wechatid", length = 50)
	public String getWechatid() {
		return this.wechatid;
	}

	public void setWechatid(String wechatid) {
		this.wechatid = wechatid;
	}

	@Column(name = "weiboid", length = 50)
	public String getWeiboid() {
		return this.weiboid;
	}

	public void setWeiboid(String weiboid) {
		this.weiboid = weiboid;
	}

	@Column(name = "qqid", length = 50)
	public String getQqid() {
		return this.qqid;
	}

	public void setQqid(String qqid) {
		this.qqid = qqid;
	}

	@Column(name = "quota")
	public Integer getQuota() {
		return this.quota;
	}

	public void setQuota(Integer quota) {
		this.quota = quota;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "social_info", length = 4000)
	public String getSocialInfo() {
		return this.socialInfo;
	}

	public void setSocialInfo(String socialInfo) {
		this.socialInfo = socialInfo;
	}

	@Column(name = "device_info", length = 4000)
	public String getDeviceInfo() {
		return this.deviceInfo;
	}

	public void setDeviceInfo(String deviceInfo) {
		this.deviceInfo = deviceInfo;
	}

	@Column(name = "contacts_info", length = 4000)
	public String getContactsInfo() {
		return this.contactsInfo;
	}

	public void setContactsInfo(String contactsInfo) {
		this.contactsInfo = contactsInfo;
	}

	@Column(name = "avatar_storeid", length = 5)
	public String getAvatarStoreid() {
		return this.avatarStoreid;
	}

	public void setAvatarStoreid(String avatarStoreid) {
		this.avatarStoreid = avatarStoreid;
	}

	@Column(name = "avatar", length = 200)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "coverimage_storeid", length = 5)
	public String getCoverimageStoreid() {
		return this.coverimageStoreid;
	}

	public void setCoverimageStoreid(String coverimageStoreid) {
		this.coverimageStoreid = coverimageStoreid;
	}

	@Column(name = "coverimage", length = 200)
	public String getCoverimage() {
		return this.coverimage;
	}

	public void setCoverimage(String coverimage) {
		this.coverimage = coverimage;
	}

	@Column(name = "idcardimage", length = 200)
	public String getIdcardimage() {
		return this.idcardimage;
	}

	public void setIdcardimage(String idcardimage) {
		this.idcardimage = idcardimage;
	}

	@Column(name = "idcardnumber", length = 50)
	public String getIdcardnumber() {
		return this.idcardnumber;
	}

	public void setIdcardnumber(String idcardnumber) {
		this.idcardnumber = idcardnumber;
	}

	@Column(name = "realname", length = 50)
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "randomstring", length = 10)
	public String getRandomstring() {
		return this.randomstring;
	}

	public void setRandomstring(String randomstring) {
		this.randomstring = randomstring;
	}

	@Column(name = "bankinfo", length = 200)
	public String getBankinfo() {
		return this.bankinfo;
	}

	public void setBankinfo(String bankinfo) {
		this.bankinfo = bankinfo;
	}

	@Column(name = "isactive", nullable = false)
	public boolean isIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	@Column(name = "activecode", length = 50)
	public String getActivecode() {
		return this.activecode;
	}

	public void setActivecode(String activecode) {
		this.activecode = activecode;
	}

	@Column(name = "alipayaccount", length = 50)
	public String getAlipayaccount() {
		return this.alipayaccount;
	}

	public void setAlipayaccount(String alipayaccount) {
		this.alipayaccount = alipayaccount;
	}

	@Column(name = "signature", length = 100)
	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	@Column(name = "region_user", length = 50)
	public String getRegionUser() {
		return this.regionUser;
	}

	public void setRegionUser(String regionUser) {
		this.regionUser = regionUser;
	}

	@Column(name = "city_user", length = 50)
	public String getCityUser() {
		return this.cityUser;
	}

	public void setCityUser(String cityUser) {
		this.cityUser = cityUser;
	}

	@Column(name = "selfintro", length = 2000)
	public String getSelfintro() {
		return this.selfintro;
	}

	public void setSelfintro(String selfintro) {
		this.selfintro = selfintro;
	}

	@Column(name = "registerby", length = 50)
	public String getRegisterby() {
		return this.registerby;
	}

	public void setRegisterby(String registerby) {
		this.registerby = registerby;
	}

}
