package com.gaopin.entity;

// Generated Dec 22, 2015 9:00:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TubeContestImages generated by hbm2java
 */
@Entity
@Table(name = "tube_contest_images")
public class TubeContestImages implements java.io.Serializable {

	private Long id;
	private String uuid;
	private Integer filesize;
	private String orgiFilename;
	private String filename;
	private String storageid;
	private String contestid;
	private String comment;
	private String userid;
	private String title;
	private String orgiTitle;
	private String caption;
	private String orgiCaption;
	private Integer status;
	private Date dateupload;
	private String approvedBy;
	private Date dateapproved;
	private Date datePhotographed;
	private Date datePhotographedApprox;
	private String displaylocation;
	private String modelReleaseStatus;
	private String propertyReleaseStatus;
	private Integer contentType;
	private Integer contentSecondType;
	private String customCreditLine;
	private Integer sizeCode;
	private String restriction;
	private String photographer;
	private Integer providerId;
	private Integer orgiLevel;
	private String photoType;
	private String licenseModel;
	private Integer contentTypeId;
	private Integer contentTypeSecondaryId;
	private Integer collectionId;
	private Integer marketingCollectionId;
	private String collectionTier;
	private Integer pricing;
	private int isInImageGroup;
	private String keyChinese;
	private String orgiKeyChinese;
	private String keyEnglish;
	private String orgiKeyEnglish;
	private String reason;
	private String metadata;
	private int voteUp;
	private int voteDown;
	private String userIp;
	private Integer ispublic;
	private Integer categoryId;
	private String extName;
	private Integer orgiWidth;
	private Integer orgiHeight;
	private int deleted;
	private String category;
	private String camera;
	private String lens;
	private String focallength;
	private String shutterspeed;
	private String aperture;
	private String iso;
	private Integer requestonline;
	private Integer copyrightid;
	private String nickname;
	private String username;

	public TubeContestImages() {
	}

	public TubeContestImages(int isInImageGroup, int voteUp, int voteDown,
			int deleted) {
		this.isInImageGroup = isInImageGroup;
		this.voteUp = voteUp;
		this.voteDown = voteDown;
		this.deleted = deleted;
	}

	public TubeContestImages(String uuid, Integer filesize,
			String orgiFilename, String filename, String storageid,
			String contestid, String comment, String userid, String title,
			String orgiTitle, String caption, String orgiCaption,
			Integer status, Date dateupload, String approvedBy,
			Date dateapproved, Date datePhotographed,
			Date datePhotographedApprox, String displaylocation,
			String modelReleaseStatus, String propertyReleaseStatus,
			Integer contentType, Integer contentSecondType,
			String customCreditLine, Integer sizeCode, String restriction,
			String photographer, Integer providerId, Integer orgiLevel,
			String photoType, String licenseModel, Integer contentTypeId,
			Integer contentTypeSecondaryId, Integer collectionId,
			Integer marketingCollectionId, String collectionTier,
			Integer pricing, int isInImageGroup, String keyChinese,
			String orgiKeyChinese, String keyEnglish, String orgiKeyEnglish,
			String reason, String metadata, int voteUp, int voteDown,
			String userIp, Integer ispublic, Integer categoryId,
			String extName, Integer orgiWidth, Integer orgiHeight, int deleted,
			String category, String camera, String lens, String focallength,
			String shutterspeed, String aperture, String iso,
			Integer requestonline, Integer copyrightid, String nickname,
			String username) {
		this.uuid = uuid;
		this.filesize = filesize;
		this.orgiFilename = orgiFilename;
		this.filename = filename;
		this.storageid = storageid;
		this.contestid = contestid;
		this.comment = comment;
		this.userid = userid;
		this.title = title;
		this.orgiTitle = orgiTitle;
		this.caption = caption;
		this.orgiCaption = orgiCaption;
		this.status = status;
		this.dateupload = dateupload;
		this.approvedBy = approvedBy;
		this.dateapproved = dateapproved;
		this.datePhotographed = datePhotographed;
		this.datePhotographedApprox = datePhotographedApprox;
		this.displaylocation = displaylocation;
		this.modelReleaseStatus = modelReleaseStatus;
		this.propertyReleaseStatus = propertyReleaseStatus;
		this.contentType = contentType;
		this.contentSecondType = contentSecondType;
		this.customCreditLine = customCreditLine;
		this.sizeCode = sizeCode;
		this.restriction = restriction;
		this.photographer = photographer;
		this.providerId = providerId;
		this.orgiLevel = orgiLevel;
		this.photoType = photoType;
		this.licenseModel = licenseModel;
		this.contentTypeId = contentTypeId;
		this.contentTypeSecondaryId = contentTypeSecondaryId;
		this.collectionId = collectionId;
		this.marketingCollectionId = marketingCollectionId;
		this.collectionTier = collectionTier;
		this.pricing = pricing;
		this.isInImageGroup = isInImageGroup;
		this.keyChinese = keyChinese;
		this.orgiKeyChinese = orgiKeyChinese;
		this.keyEnglish = keyEnglish;
		this.orgiKeyEnglish = orgiKeyEnglish;
		this.reason = reason;
		this.metadata = metadata;
		this.voteUp = voteUp;
		this.voteDown = voteDown;
		this.userIp = userIp;
		this.ispublic = ispublic;
		this.categoryId = categoryId;
		this.extName = extName;
		this.orgiWidth = orgiWidth;
		this.orgiHeight = orgiHeight;
		this.deleted = deleted;
		this.category = category;
		this.camera = camera;
		this.lens = lens;
		this.focallength = focallength;
		this.shutterspeed = shutterspeed;
		this.aperture = aperture;
		this.iso = iso;
		this.requestonline = requestonline;
		this.copyrightid = copyrightid;
		this.nickname = nickname;
		this.username = username;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "UUID", length = 50)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "Filesize")
	public Integer getFilesize() {
		return this.filesize;
	}

	public void setFilesize(Integer filesize) {
		this.filesize = filesize;
	}

	@Column(name = "OrgiFilename", length = 50)
	public String getOrgiFilename() {
		return this.orgiFilename;
	}

	public void setOrgiFilename(String orgiFilename) {
		this.orgiFilename = orgiFilename;
	}

	@Column(name = "Filename", length = 50)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "Storageid", length = 5)
	public String getStorageid() {
		return this.storageid;
	}

	public void setStorageid(String storageid) {
		this.storageid = storageid;
	}

	@Column(name = "contestid", length = 10)
	public String getContestid() {
		return this.contestid;
	}

	public void setContestid(String contestid) {
		this.contestid = contestid;
	}

	@Column(name = "comment", length = 1000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "Userid", length = 50)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "Title", length = 1000)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "OrgiTitle", length = 1000)
	public String getOrgiTitle() {
		return this.orgiTitle;
	}

	public void setOrgiTitle(String orgiTitle) {
		this.orgiTitle = orgiTitle;
	}

	@Column(name = "Caption", length = 1000)
	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	@Column(name = "OrgiCaption", length = 1000)
	public String getOrgiCaption() {
		return this.orgiCaption;
	}

	public void setOrgiCaption(String orgiCaption) {
		this.orgiCaption = orgiCaption;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Dateupload", length = 19)
	public Date getDateupload() {
		return this.dateupload;
	}

	public void setDateupload(Date dateupload) {
		this.dateupload = dateupload;
	}

	@Column(name = "ApprovedBy", length = 100)
	public String getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Dateapproved", length = 19)
	public Date getDateapproved() {
		return this.dateapproved;
	}

	public void setDateapproved(Date dateapproved) {
		this.dateapproved = dateapproved;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePhotographed", length = 19)
	public Date getDatePhotographed() {
		return this.datePhotographed;
	}

	public void setDatePhotographed(Date datePhotographed) {
		this.datePhotographed = datePhotographed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePhotographedApprox", length = 19)
	public Date getDatePhotographedApprox() {
		return this.datePhotographedApprox;
	}

	public void setDatePhotographedApprox(Date datePhotographedApprox) {
		this.datePhotographedApprox = datePhotographedApprox;
	}

	@Column(name = "Displaylocation", length = 200)
	public String getDisplaylocation() {
		return this.displaylocation;
	}

	public void setDisplaylocation(String displaylocation) {
		this.displaylocation = displaylocation;
	}

	@Column(name = "ModelReleaseStatus", length = 10)
	public String getModelReleaseStatus() {
		return this.modelReleaseStatus;
	}

	public void setModelReleaseStatus(String modelReleaseStatus) {
		this.modelReleaseStatus = modelReleaseStatus;
	}

	@Column(name = "PropertyReleaseStatus", length = 10)
	public String getPropertyReleaseStatus() {
		return this.propertyReleaseStatus;
	}

	public void setPropertyReleaseStatus(String propertyReleaseStatus) {
		this.propertyReleaseStatus = propertyReleaseStatus;
	}

	@Column(name = "ContentType")
	public Integer getContentType() {
		return this.contentType;
	}

	public void setContentType(Integer contentType) {
		this.contentType = contentType;
	}

	@Column(name = "ContentSecondType")
	public Integer getContentSecondType() {
		return this.contentSecondType;
	}

	public void setContentSecondType(Integer contentSecondType) {
		this.contentSecondType = contentSecondType;
	}

	@Column(name = "CustomCreditLine", length = 200)
	public String getCustomCreditLine() {
		return this.customCreditLine;
	}

	public void setCustomCreditLine(String customCreditLine) {
		this.customCreditLine = customCreditLine;
	}

	@Column(name = "SizeCode")
	public Integer getSizeCode() {
		return this.sizeCode;
	}

	public void setSizeCode(Integer sizeCode) {
		this.sizeCode = sizeCode;
	}

	@Column(name = "Restriction", length = 100)
	public String getRestriction() {
		return this.restriction;
	}

	public void setRestriction(String restriction) {
		this.restriction = restriction;
	}

	@Column(name = "Photographer", length = 100)
	public String getPhotographer() {
		return this.photographer;
	}

	public void setPhotographer(String photographer) {
		this.photographer = photographer;
	}

	@Column(name = "ProviderId")
	public Integer getProviderId() {
		return this.providerId;
	}

	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	@Column(name = "orgiLevel")
	public Integer getOrgiLevel() {
		return this.orgiLevel;
	}

	public void setOrgiLevel(Integer orgiLevel) {
		this.orgiLevel = orgiLevel;
	}

	@Column(name = "PhotoType", length = 100)
	public String getPhotoType() {
		return this.photoType;
	}

	public void setPhotoType(String photoType) {
		this.photoType = photoType;
	}

	@Column(name = "LicenseModel", length = 4)
	public String getLicenseModel() {
		return this.licenseModel;
	}

	public void setLicenseModel(String licenseModel) {
		this.licenseModel = licenseModel;
	}

	@Column(name = "ContentTypeId")
	public Integer getContentTypeId() {
		return this.contentTypeId;
	}

	public void setContentTypeId(Integer contentTypeId) {
		this.contentTypeId = contentTypeId;
	}

	@Column(name = "ContentTypeSecondaryId")
	public Integer getContentTypeSecondaryId() {
		return this.contentTypeSecondaryId;
	}

	public void setContentTypeSecondaryId(Integer contentTypeSecondaryId) {
		this.contentTypeSecondaryId = contentTypeSecondaryId;
	}

	@Column(name = "CollectionId")
	public Integer getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(Integer collectionId) {
		this.collectionId = collectionId;
	}

	@Column(name = "MarketingCollectionId")
	public Integer getMarketingCollectionId() {
		return this.marketingCollectionId;
	}

	public void setMarketingCollectionId(Integer marketingCollectionId) {
		this.marketingCollectionId = marketingCollectionId;
	}

	@Column(name = "CollectionTier", length = 30)
	public String getCollectionTier() {
		return this.collectionTier;
	}

	public void setCollectionTier(String collectionTier) {
		this.collectionTier = collectionTier;
	}

	@Column(name = "Pricing")
	public Integer getPricing() {
		return this.pricing;
	}

	public void setPricing(Integer pricing) {
		this.pricing = pricing;
	}

	@Column(name = "IsInImageGroup", nullable = false)
	public int getIsInImageGroup() {
		return this.isInImageGroup;
	}

	public void setIsInImageGroup(int isInImageGroup) {
		this.isInImageGroup = isInImageGroup;
	}

	@Column(name = "keyChinese", length = 16777215)
	public String getKeyChinese() {
		return this.keyChinese;
	}

	public void setKeyChinese(String keyChinese) {
		this.keyChinese = keyChinese;
	}

	@Column(name = "OrgiKeyChinese", length = 16777215)
	public String getOrgiKeyChinese() {
		return this.orgiKeyChinese;
	}

	public void setOrgiKeyChinese(String orgiKeyChinese) {
		this.orgiKeyChinese = orgiKeyChinese;
	}

	@Column(name = "keyEnglish", length = 16777215)
	public String getKeyEnglish() {
		return this.keyEnglish;
	}

	public void setKeyEnglish(String keyEnglish) {
		this.keyEnglish = keyEnglish;
	}

	@Column(name = "OrgiKeyEnglish", length = 16777215)
	public String getOrgiKeyEnglish() {
		return this.orgiKeyEnglish;
	}

	public void setOrgiKeyEnglish(String orgiKeyEnglish) {
		this.orgiKeyEnglish = orgiKeyEnglish;
	}

	@Column(name = "Reason", length = 200)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "metadata", length = 16777215)
	public String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

	@Column(name = "VoteUp", nullable = false)
	public int getVoteUp() {
		return this.voteUp;
	}

	public void setVoteUp(int voteUp) {
		this.voteUp = voteUp;
	}

	@Column(name = "VoteDown", nullable = false)
	public int getVoteDown() {
		return this.voteDown;
	}

	public void setVoteDown(int voteDown) {
		this.voteDown = voteDown;
	}

	@Column(name = "UserIp", length = 50)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "ispublic")
	public Integer getIspublic() {
		return this.ispublic;
	}

	public void setIspublic(Integer ispublic) {
		this.ispublic = ispublic;
	}

	@Column(name = "categoryId")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "extName", length = 10)
	public String getExtName() {
		return this.extName;
	}

	public void setExtName(String extName) {
		this.extName = extName;
	}

	@Column(name = "orgi_width")
	public Integer getOrgiWidth() {
		return this.orgiWidth;
	}

	public void setOrgiWidth(Integer orgiWidth) {
		this.orgiWidth = orgiWidth;
	}

	@Column(name = "orgi_height")
	public Integer getOrgiHeight() {
		return this.orgiHeight;
	}

	public void setOrgiHeight(Integer orgiHeight) {
		this.orgiHeight = orgiHeight;
	}

	@Column(name = "deleted", nullable = false)
	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	@Column(name = "category", length = 500)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "camera", length = 100)
	public String getCamera() {
		return this.camera;
	}

	public void setCamera(String camera) {
		this.camera = camera;
	}

	@Column(name = "lens", length = 100)
	public String getLens() {
		return this.lens;
	}

	public void setLens(String lens) {
		this.lens = lens;
	}

	@Column(name = "focallength", length = 100)
	public String getFocallength() {
		return this.focallength;
	}

	public void setFocallength(String focallength) {
		this.focallength = focallength;
	}

	@Column(name = "shutterspeed", length = 100)
	public String getShutterspeed() {
		return this.shutterspeed;
	}

	public void setShutterspeed(String shutterspeed) {
		this.shutterspeed = shutterspeed;
	}

	@Column(name = "aperture", length = 100)
	public String getAperture() {
		return this.aperture;
	}

	public void setAperture(String aperture) {
		this.aperture = aperture;
	}

	@Column(name = "iso", length = 50)
	public String getIso() {
		return this.iso;
	}

	public void setIso(String iso) {
		this.iso = iso;
	}

	@Column(name = "requestonline")
	public Integer getRequestonline() {
		return this.requestonline;
	}

	public void setRequestonline(Integer requestonline) {
		this.requestonline = requestonline;
	}

	@Column(name = "copyrightid")
	public Integer getCopyrightid() {
		return this.copyrightid;
	}

	public void setCopyrightid(Integer copyrightid) {
		this.copyrightid = copyrightid;
	}

	@Column(name = "nickname", length = 50)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
