package com.gaopin.entity;

// Generated Dec 18, 2015 2:32:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TubeContestAwards generated by hbm2java
 */
@Entity
@Table(name = "tube_contest_awards")
public class TubeContestAwards implements java.io.Serializable {

	private Integer id;
	private String contestid;
	private String imageid;
	private String userid;
	private int awardclass;
	private Date createtime;
	private String comment;

	public TubeContestAwards() {
	}

	public TubeContestAwards(String contestid, String imageid, String userid,
			int awardclass) {
		this.contestid = contestid;
		this.imageid = imageid;
		this.userid = userid;
		this.awardclass = awardclass;
	}

	public TubeContestAwards(String contestid, String imageid, String userid,
			int awardclass, Date createtime, String comment) {
		this.contestid = contestid;
		this.imageid = imageid;
		this.userid = userid;
		this.awardclass = awardclass;
		this.createtime = createtime;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "contestid", nullable = false, length = 10)
	public String getContestid() {
		return this.contestid;
	}

	public void setContestid(String contestid) {
		this.contestid = contestid;
	}

	@Column(name = "imageid", nullable = false, length = 50)
	public String getImageid() {
		return this.imageid;
	}

	public void setImageid(String imageid) {
		this.imageid = imageid;
	}

	@Column(name = "userid", nullable = false, length = 50)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "awardclass", nullable = false)
	public int getAwardclass() {
		return this.awardclass;
	}

	public void setAwardclass(int awardclass) {
		this.awardclass = awardclass;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
