package com.gaopin.entity;

// Generated Dec 18, 2015 2:32:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TubeContest generated by hbm2java
 */
@Entity
@Table(name = "tube_contest")
public class TubeContest implements java.io.Serializable {

	private Integer id;
	private String contestid;
	private String contestname;
	private String contestdesc;
	private Date startdate;
	private Date enddate;
	private int status;
	private String coverimage1;
	private String coverimage2;
	private Integer sequence;
	private Integer limit;
	private Integer showindex;
	private int imageamount;

	public TubeContest() {
	}

	public TubeContest(String contestid, int status, int imageamount) {
		this.contestid = contestid;
		this.status = status;
		this.imageamount = imageamount;
	}

	public TubeContest(String contestid, String contestname,
			String contestdesc, Date startdate, Date enddate, int status,
			String coverimage1, String coverimage2, Integer sequence,
			Integer limit, Integer showindex, int imageamount) {
		this.contestid = contestid;
		this.contestname = contestname;
		this.contestdesc = contestdesc;
		this.startdate = startdate;
		this.enddate = enddate;
		this.status = status;
		this.coverimage1 = coverimage1;
		this.coverimage2 = coverimage2;
		this.sequence = sequence;
		this.limit = limit;
		this.showindex = showindex;
		this.imageamount = imageamount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "contestid", nullable = false, length = 10)
	public String getContestid() {
		return this.contestid;
	}

	public void setContestid(String contestid) {
		this.contestid = contestid;
	}

	@Column(name = "contestname", length = 100)
	public String getContestname() {
		return this.contestname;
	}

	public void setContestname(String contestname) {
		this.contestname = contestname;
	}

	@Column(name = "contestdesc", length = 2000)
	public String getContestdesc() {
		return this.contestdesc;
	}

	public void setContestdesc(String contestdesc) {
		this.contestdesc = contestdesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdate", length = 19)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enddate", length = 19)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "coverimage1", length = 1000)
	public String getCoverimage1() {
		return this.coverimage1;
	}

	public void setCoverimage1(String coverimage1) {
		this.coverimage1 = coverimage1;
	}

	@Column(name = "coverimage2", length = 1000)
	public String getCoverimage2() {
		return this.coverimage2;
	}

	public void setCoverimage2(String coverimage2) {
		this.coverimage2 = coverimage2;
	}

	@Column(name = "sequence")
	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	@Column(name = "limit")
	public Integer getLimit() {
		return this.limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	@Column(name = "showindex")
	public Integer getShowindex() {
		return this.showindex;
	}

	public void setShowindex(Integer showindex) {
		this.showindex = showindex;
	}

	@Column(name = "imageamount", nullable = false)
	public int getImageamount() {
		return this.imageamount;
	}

	public void setImageamount(int imageamount) {
		this.imageamount = imageamount;
	}

}
