package com.gaopin.entity;

// Generated Dec 18, 2015 2:32:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TubeImages generated by hbm2java
 */
@Entity
@Table(name = "tube_images")
public class TubeImages implements java.io.Serializable {

	private Long id;
	private String orgiId;
	private String gaopinId;
	private String userId;
	private String uuid;
	private String fileName;
	private Date onlineTime;
	private Integer status;

	public TubeImages() {
	}

	public TubeImages(String orgiId, String gaopinId, String userId,
			String uuid, String fileName, Date onlineTime, Integer status) {
		this.orgiId = orgiId;
		this.gaopinId = gaopinId;
		this.userId = userId;
		this.uuid = uuid;
		this.fileName = fileName;
		this.onlineTime = onlineTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "OrgiID", length = 50)
	public String getOrgiId() {
		return this.orgiId;
	}

	public void setOrgiId(String orgiId) {
		this.orgiId = orgiId;
	}

	@Column(name = "GaopinId", length = 30)
	public String getGaopinId() {
		return this.gaopinId;
	}

	public void setGaopinId(String gaopinId) {
		this.gaopinId = gaopinId;
	}

	@Column(name = "UserId", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "UUID", length = 50)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "FileName", length = 50)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OnlineTime", length = 19)
	public Date getOnlineTime() {
		return this.onlineTime;
	}

	public void setOnlineTime(Date onlineTime) {
		this.onlineTime = onlineTime;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
