package com.gaopin.entity;

// Generated Sep 22, 2015 3:45:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrImagegallery generated by hbm2java
 */
@Entity
@Table(name = "fr_imagegallery", catalog = "gaopin_images")
public class FrImagegallery implements java.io.Serializable {

	private Integer id;
	private String name;
	private String info;
	private Integer type;
	private Integer status;
	private Date createTime;
	private Date updateTime;
	private Integer updateUser;
	private String galleryCap;
	private String galleryDesc;

	public FrImagegallery() {
	}

	public FrImagegallery(String name, String info, Integer type,
			Integer status, Date createTime, Date updateTime, Integer updateUser, String galleryCap, String galleryDesc) {
		this.name = name;
		this.info = info;
		this.type = type;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
		this.galleryCap = galleryCap;
		this.galleryDesc = galleryDesc;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "info", length = 256)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_user")
	public Integer getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}
	
	@Column(name = "gallery_cap", length = 256)
	public String getGalleryCap() {
		return galleryCap;
	}

	public void setGalleryCap(String galleryCap) {
		this.galleryCap = galleryCap;
	}

	@Column(name = "gallery_desc", length = 1024)
	public String getGalleryDesc() {
		return galleryDesc;
	}

	public void setGalleryDesc(String galleryDesc) {
		this.galleryDesc = galleryDesc;
	}

}
