package com.gaopin.entity;

// Generated May 14, 2015 5:40:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrMotionCollection generated by hbm2java
 */
@Entity
@Table(name = "fr_motion_collection", catalog = "gaopin_images")
public class FrMotionCollection implements java.io.Serializable {

	private Integer id;
	private Integer parentId;
	private String name;
	private String showName;
	private String pricingTier;
	private String caption;
	private String intro;
	private Integer categoryId;
	private Integer secondCategoryId;
	private Integer cpId;
	private String brandName;
	private Integer imageNum;
	private Integer licenseType;
	private Integer status;
	private Integer score;
	private Integer level;
	private String coverUrl;
	private Byte showSimilar;
	private String template;
	private Integer sortId;
	private Date createTime;
	private Date updateTime;
	private Date authorizedEndDate;
	private Date lastUpdate;
	private Integer lastEditor;
	private Integer exContenttypeId;
	private Integer exContenttypeSecondId;

	public FrMotionCollection() {
	}

	public FrMotionCollection(Integer parentId, String name, String showName,
			String pricingTier, String caption, String intro,
			Integer categoryId, Integer secondCategoryId, Integer cpId,
			String brandName, Integer imageNum, Integer licenseType,
			Integer status, Integer score, Integer level, String coverUrl,
			Byte showSimilar, String template, Integer sortId, Date createTime,
			Date updateTime, Date authorizedEndDate, Date lastUpdate,
			Integer lastEditor, Integer exContenttypeId,
			Integer exContenttypeSecondId) {
		this.parentId = parentId;
		this.name = name;
		this.showName = showName;
		this.pricingTier = pricingTier;
		this.caption = caption;
		this.intro = intro;
		this.categoryId = categoryId;
		this.secondCategoryId = secondCategoryId;
		this.cpId = cpId;
		this.brandName = brandName;
		this.imageNum = imageNum;
		this.licenseType = licenseType;
		this.status = status;
		this.score = score;
		this.level = level;
		this.coverUrl = coverUrl;
		this.showSimilar = showSimilar;
		this.template = template;
		this.sortId = sortId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.authorizedEndDate = authorizedEndDate;
		this.lastUpdate = lastUpdate;
		this.lastEditor = lastEditor;
		this.exContenttypeId = exContenttypeId;
		this.exContenttypeSecondId = exContenttypeSecondId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "show_name", length = 100)
	public String getShowName() {
		return this.showName;
	}

	public void setShowName(String showName) {
		this.showName = showName;
	}

	@Column(name = "pricing_tier", length = 30)
	public String getPricingTier() {
		return this.pricingTier;
	}

	public void setPricingTier(String pricingTier) {
		this.pricingTier = pricingTier;
	}

	@Column(name = "caption", length = 200)
	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	@Column(name = "intro", length = 4000)
	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "second_category_id")
	public Integer getSecondCategoryId() {
		return this.secondCategoryId;
	}

	public void setSecondCategoryId(Integer secondCategoryId) {
		this.secondCategoryId = secondCategoryId;
	}

	@Column(name = "cp_id")
	public Integer getCpId() {
		return this.cpId;
	}

	public void setCpId(Integer cpId) {
		this.cpId = cpId;
	}

	@Column(name = "brand_name", length = 100)
	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	@Column(name = "image_num")
	public Integer getImageNum() {
		return this.imageNum;
	}

	public void setImageNum(Integer imageNum) {
		this.imageNum = imageNum;
	}

	@Column(name = "license_type")
	public Integer getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(Integer licenseType) {
		this.licenseType = licenseType;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "cover_url", length = 1000)
	public String getCoverUrl() {
		return this.coverUrl;
	}

	public void setCoverUrl(String coverUrl) {
		this.coverUrl = coverUrl;
	}

	@Column(name = "show_similar")
	public Byte getShowSimilar() {
		return this.showSimilar;
	}

	public void setShowSimilar(Byte showSimilar) {
		this.showSimilar = showSimilar;
	}

	@Column(name = "template", length = 16777215)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	@Column(name = "sort_id")
	public Integer getSortId() {
		return this.sortId;
	}

	public void setSortId(Integer sortId) {
		this.sortId = sortId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "authorized_end_date", length = 19)
	public Date getAuthorizedEndDate() {
		return this.authorizedEndDate;
	}

	public void setAuthorizedEndDate(Date authorizedEndDate) {
		this.authorizedEndDate = authorizedEndDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "last_editor")
	public Integer getLastEditor() {
		return this.lastEditor;
	}

	public void setLastEditor(Integer lastEditor) {
		this.lastEditor = lastEditor;
	}

	@Column(name = "ex_contenttype_id")
	public Integer getExContenttypeId() {
		return this.exContenttypeId;
	}

	public void setExContenttypeId(Integer exContenttypeId) {
		this.exContenttypeId = exContenttypeId;
	}

	@Column(name = "ex_contenttype_second_id")
	public Integer getExContenttypeSecondId() {
		return this.exContenttypeSecondId;
	}

	public void setExContenttypeSecondId(Integer exContenttypeSecondId) {
		this.exContenttypeSecondId = exContenttypeSecondId;
	}

}
