package com.gaopin.entity;

// Generated May 14, 2015 5:40:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobMotionOnline generated by hbm2java
 */
@Entity
@Table(name = "job_motion_online", catalog = "gaopin_images")
public class JobMotionOnline implements java.io.Serializable {

	private Integer id;
	private Long motionId;
	private String gaopinId;
	private Integer status;
	private Integer type;
	private Integer userId;
	private Integer tryTimes;
	private Date createTime;
	private Date updateTime;
	private Date validTime;

	public JobMotionOnline() {
	}

	public JobMotionOnline(Long motionId, String gaopinId, Integer status,
			Integer type, Integer userId, Integer tryTimes, Date createTime,
			Date updateTime, Date validTime) {
		this.motionId = motionId;
		this.gaopinId = gaopinId;
		this.status = status;
		this.type = type;
		this.userId = userId;
		this.tryTimes = tryTimes;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.validTime = validTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "motion_id")
	public Long getMotionId() {
		return this.motionId;
	}

	public void setMotionId(Long motionId) {
		this.motionId = motionId;
	}

	@Column(name = "gaopin_id", length = 50)
	public String getGaopinId() {
		return this.gaopinId;
	}

	public void setGaopinId(String gaopinId) {
		this.gaopinId = gaopinId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "try_times")
	public Integer getTryTimes() {
		return this.tryTimes;
	}

	public void setTryTimes(Integer tryTimes) {
		this.tryTimes = tryTimes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_time", length = 19)
	public Date getValidTime() {
		return this.validTime;
	}

	public void setValidTime(Date validTime) {
		this.validTime = validTime;
	}

}
