package com.gaopin.entity;

// Generated Nov 13, 2015 9:48:02 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LtIpExclusive generated by hbm2java
 */
@Entity
@Table(name = "lt_ip_exclusive", catalog = "gaopin_images")
public class LtIpExclusive implements java.io.Serializable {

	private Integer id;
	private String ipaddress;
	private Integer status;

	public LtIpExclusive() {
	}

	public LtIpExclusive(String ipaddress, Integer status) {
		this.ipaddress = ipaddress;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ipaddress", length = 50)
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
