package com.gaopin.entity;

// Generated May 14, 2015 5:40:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * OrgiMotions generated by hbm2java
 */
@Entity
@Table(name = "orgi_motions", catalog = "gaopin_images", uniqueConstraints = @UniqueConstraint(columnNames = "GaopinID"))
public class OrgiMotions implements java.io.Serializable {

	private Long id;
	private String motionUid;
	private String orgiId;
	private String gaopinId;
	private Integer storageId;
	private String title;
	private String caption;
	private String codec;
	private String fileFormat;
	private Integer height;
	private Integer width;
	private String fps;
	private String originalInterlacedProgressive;
	private Float duration;
	private Integer fileSize;
	private String cameraUsed;
	private String mediaType;
	private String motionSpeed;
	private String motionColor;
	private String originalCaption;
	private String modelIdentification;
	private String licenseModel;
	private Integer contentTypeId;
	private Integer contentTypeSecondaryId;
	private String subject;
	private String subjectSecondary;
	private Integer photographerId;
	private String providerSource;
	private String credit;
	private String customCreditLine;
	private String manualArchiveCollection;
	private String automatedArchiveCollections;
	private String displaylocation;
	private Integer contractId;
	private String contractName;
	private Byte modelReleaseStatus;
	private Byte propertyReleaseStatus;
	private Integer representationrights;
	private String modelReleaseIds;
	private String propertyReleaseIds;
	private String mediaRatingText;
	private Date dateShot;
	private String dateShotApprox;
	private Date leftShotDate;
	private Date rightShotDate;
	private Integer fineArtCopyrightStatus;
	private String fineArtCreditLine;
	private Boolean isInMotionSet;
	private Boolean isInRfcd;
	private Boolean isInMotionGroup;
	private Date dateExpiration;
	private Date datePublished;
	private Date domesticEmbargoDate;
	private Date internationalEmbargoDate;
	private Integer placement;
	private Integer pricing;
	private Boolean rightOfFirstSale;
	private String outlineSessionUid;
	private Boolean isOutline;
	private String outlineMagazineName;
	private Integer marketingCollectionId;
	private Integer collectionId;
	private String collectionTier;
	private Date createdAt;
	private Date changedAt;
	private String keyEnglish;
	private String keyChinese;
	private String termsSpecial;
	private String restrictionIds;
	private String contentWarningIds;
	private Integer maxSizeCode;
	private Integer selector;
	private Date selectedDate;
	private Integer lastEditor;
	private Date inputDate;
	private Integer selectionStatus;
	private Integer status;
	private Boolean searchableInternal;
	private Boolean searchableExternal;
	private String renderings;
	private String colorAppearance;
	private String originalMediaFormat;
	private Integer providerId;
	private String originalFilename;
	private String iptc;
	private String salesData;
	private String remark;
	private String aspectRatio;
	private String orientation;
	private String orgiTitle;
	private Integer orgiMediaRatingText;
	private String sourcePreFlvPath;
	private String sourcePreMp4path;
	private String sourceDetMp4path;
	private Integer onlineType;
	
	public OrgiMotions() {
	}

	public OrgiMotions(String motionUid, String orgiId, String gaopinId,
			Integer storageId, String title, String caption, String codec,
			String fileFormat, Integer height, Integer width, String fps,
			String originalInterlacedProgressive, Float duration,
			Integer fileSize, String cameraUsed, String mediaType,
			String motionSpeed, String motionColor, String originalCaption,
			String modelIdentification, String licenseModel,
			Integer contentTypeId, Integer contentTypeSecondaryId,
			String subject, String subjectSecondary, Integer photographerId,
			String providerSource, String credit, String customCreditLine,
			String manualArchiveCollection, String automatedArchiveCollections,
			String displaylocation, Integer contractId, String contractName,
			Byte modelReleaseStatus, Byte propertyReleaseStatus,
			Integer representationrights, String modelReleaseIds,
			String propertyReleaseIds, String mediaRatingText, Date dateShot,
			String dateShotApprox, Date leftShotDate, Date rightShotDate,
			Integer fineArtCopyrightStatus, String fineArtCreditLine,
			Boolean isInMotionSet, Boolean isInRfcd, Boolean isInMotionGroup,
			Date dateExpiration, Date datePublished, Date domesticEmbargoDate,
			Date internationalEmbargoDate, Integer placement, Integer pricing,
			Boolean rightOfFirstSale, String outlineSessionUid,
			Boolean isOutline, String outlineMagazineName,
			Integer marketingCollectionId, Integer collectionId,
			String collectionTier, Date createdAt, Date changedAt,
			String keyEnglish, String keyChinese, String termsSpecial,
			String restrictionIds, String contentWarningIds,
			Integer maxSizeCode, Integer selector, Date selectedDate,
			Integer lastEditor, Date inputDate, Integer selectionStatus,
			Integer status, Boolean searchableInternal,
			Boolean searchableExternal, String renderings,
			String colorAppearance, String originalMediaFormat,
			Integer providerId, String originalFilename, String iptc,
			String salesData, String remark, String aspectRatio,
			String orientation, String orgiTitle, Integer orgiMediaRatingText,
			String sourcePreFlvPath, String sourcePreMp4path,
			String sourceDetMp4path, Integer onlineType) {
		this.motionUid = motionUid;
		this.orgiId = orgiId;
		this.gaopinId = gaopinId;
		this.storageId = storageId;
		this.title = title;
		this.caption = caption;
		this.codec = codec;
		this.fileFormat = fileFormat;
		this.height = height;
		this.width = width;
		this.fps = fps;
		this.originalInterlacedProgressive = originalInterlacedProgressive;
		this.duration = duration;
		this.fileSize = fileSize;
		this.cameraUsed = cameraUsed;
		this.mediaType = mediaType;
		this.motionSpeed = motionSpeed;
		this.motionColor = motionColor;
		this.originalCaption = originalCaption;
		this.modelIdentification = modelIdentification;
		this.licenseModel = licenseModel;
		this.contentTypeId = contentTypeId;
		this.contentTypeSecondaryId = contentTypeSecondaryId;
		this.subject = subject;
		this.subjectSecondary = subjectSecondary;
		this.photographerId = photographerId;
		this.providerSource = providerSource;
		this.credit = credit;
		this.customCreditLine = customCreditLine;
		this.manualArchiveCollection = manualArchiveCollection;
		this.automatedArchiveCollections = automatedArchiveCollections;
		this.displaylocation = displaylocation;
		this.contractId = contractId;
		this.contractName = contractName;
		this.modelReleaseStatus = modelReleaseStatus;
		this.propertyReleaseStatus = propertyReleaseStatus;
		this.representationrights = representationrights;
		this.modelReleaseIds = modelReleaseIds;
		this.propertyReleaseIds = propertyReleaseIds;
		this.mediaRatingText = mediaRatingText;
		this.dateShot = dateShot;
		this.dateShotApprox = dateShotApprox;
		this.leftShotDate = leftShotDate;
		this.rightShotDate = rightShotDate;
		this.fineArtCopyrightStatus = fineArtCopyrightStatus;
		this.fineArtCreditLine = fineArtCreditLine;
		this.isInMotionSet = isInMotionSet;
		this.isInRfcd = isInRfcd;
		this.isInMotionGroup = isInMotionGroup;
		this.dateExpiration = dateExpiration;
		this.datePublished = datePublished;
		this.domesticEmbargoDate = domesticEmbargoDate;
		this.internationalEmbargoDate = internationalEmbargoDate;
		this.placement = placement;
		this.pricing = pricing;
		this.rightOfFirstSale = rightOfFirstSale;
		this.outlineSessionUid = outlineSessionUid;
		this.isOutline = isOutline;
		this.outlineMagazineName = outlineMagazineName;
		this.marketingCollectionId = marketingCollectionId;
		this.collectionId = collectionId;
		this.collectionTier = collectionTier;
		this.createdAt = createdAt;
		this.changedAt = changedAt;
		this.keyEnglish = keyEnglish;
		this.keyChinese = keyChinese;
		this.termsSpecial = termsSpecial;
		this.restrictionIds = restrictionIds;
		this.contentWarningIds = contentWarningIds;
		this.maxSizeCode = maxSizeCode;
		this.selector = selector;
		this.selectedDate = selectedDate;
		this.lastEditor = lastEditor;
		this.inputDate = inputDate;
		this.selectionStatus = selectionStatus;
		this.status = status;
		this.searchableInternal = searchableInternal;
		this.searchableExternal = searchableExternal;
		this.renderings = renderings;
		this.colorAppearance = colorAppearance;
		this.originalMediaFormat = originalMediaFormat;
		this.providerId = providerId;
		this.originalFilename = originalFilename;
		this.iptc = iptc;
		this.salesData = salesData;
		this.remark = remark;
		this.aspectRatio = aspectRatio;
		this.orientation = orientation;
		this.orgiTitle = orgiTitle;
		this.orgiMediaRatingText = orgiMediaRatingText;
		this.sourcePreFlvPath = sourcePreFlvPath;
		this.sourcePreMp4path = sourcePreMp4path;
		this.sourceDetMp4path = sourceDetMp4path;
		this.onlineType = onlineType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "MotionUID", length = 40)
	public String getMotionUid() {
		return this.motionUid;
	}

	public void setMotionUid(String motionUid) {
		this.motionUid = motionUid;
	}

	@Column(name = "OrgiID", length = 50)
	public String getOrgiId() {
		return this.orgiId;
	}

	public void setOrgiId(String orgiId) {
		this.orgiId = orgiId;
	}

	@Column(name = "GaopinID", unique = true, length = 30)
	public String getGaopinId() {
		return this.gaopinId;
	}

	public void setGaopinId(String gaopinId) {
		this.gaopinId = gaopinId;
	}

	@Column(name = "StorageID")
	public Integer getStorageId() {
		return this.storageId;
	}

	public void setStorageId(Integer storageId) {
		this.storageId = storageId;
	}

	@Column(name = "Title", length = 1000)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Caption", length = 1000)
	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	@Column(name = "Codec", length = 100)
	public String getCodec() {
		return this.codec;
	}

	public void setCodec(String codec) {
		this.codec = codec;
	}

	@Column(name = "fileFormat", length = 100)
	public String getFileFormat() {
		return this.fileFormat;
	}

	public void setFileFormat(String fileFormat) {
		this.fileFormat = fileFormat;
	}

	@Column(name = "Height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "Width")
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "FPS", length = 10)
	public String getFps() {
		return this.fps;
	}

	public void setFps(String fps) {
		this.fps = fps;
	}

	@Column(name = "OriginalInterlacedProgressive", length = 100)
	public String getOriginalInterlacedProgressive() {
		return this.originalInterlacedProgressive;
	}

	public void setOriginalInterlacedProgressive(
			String originalInterlacedProgressive) {
		this.originalInterlacedProgressive = originalInterlacedProgressive;
	}

	@Column(name = "Duration", precision = 12, scale = 0)
	public Float getDuration() {
		return this.duration;
	}

	public void setDuration(Float duration) {
		this.duration = duration;
	}

	@Column(name = "FileSize")
	public Integer getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name = "CameraUsed", length = 100)
	public String getCameraUsed() {
		return this.cameraUsed;
	}

	public void setCameraUsed(String cameraUsed) {
		this.cameraUsed = cameraUsed;
	}

	@Column(name = "MediaType", length = 100)
	public String getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

	@Column(name = "MotionSpeed", length = 100)
	public String getMotionSpeed() {
		return this.motionSpeed;
	}

	public void setMotionSpeed(String motionSpeed) {
		this.motionSpeed = motionSpeed;
	}

	@Column(name = "motionColor", length = 100)
	public String getMotionColor() {
		return this.motionColor;
	}

	public void setMotionColor(String motionColor) {
		this.motionColor = motionColor;
	}

	@Column(name = "OriginalCaption", length = 1000)
	public String getOriginalCaption() {
		return this.originalCaption;
	}

	public void setOriginalCaption(String originalCaption) {
		this.originalCaption = originalCaption;
	}

	@Column(name = "ModelIdentification", length = 1000)
	public String getModelIdentification() {
		return this.modelIdentification;
	}

	public void setModelIdentification(String modelIdentification) {
		this.modelIdentification = modelIdentification;
	}

	@Column(name = "LicenseModel", length = 4)
	public String getLicenseModel() {
		return this.licenseModel;
	}

	public void setLicenseModel(String licenseModel) {
		this.licenseModel = licenseModel;
	}

	@Column(name = "ContentTypeId")
	public Integer getContentTypeId() {
		return this.contentTypeId;
	}

	public void setContentTypeId(Integer contentTypeId) {
		this.contentTypeId = contentTypeId;
	}

	@Column(name = "ContentTypeSecondaryId")
	public Integer getContentTypeSecondaryId() {
		return this.contentTypeSecondaryId;
	}

	public void setContentTypeSecondaryId(Integer contentTypeSecondaryId) {
		this.contentTypeSecondaryId = contentTypeSecondaryId;
	}

	@Column(name = "Subject", length = 100)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "SubjectSecondary", length = 100)
	public String getSubjectSecondary() {
		return this.subjectSecondary;
	}

	public void setSubjectSecondary(String subjectSecondary) {
		this.subjectSecondary = subjectSecondary;
	}

	@Column(name = "PhotographerId")
	public Integer getPhotographerId() {
		return this.photographerId;
	}

	public void setPhotographerId(Integer photographerId) {
		this.photographerId = photographerId;
	}

	@Column(name = "ProviderSource", length = 100)
	public String getProviderSource() {
		return this.providerSource;
	}

	public void setProviderSource(String providerSource) {
		this.providerSource = providerSource;
	}

	@Column(name = "Credit", length = 50)
	public String getCredit() {
		return this.credit;
	}

	public void setCredit(String credit) {
		this.credit = credit;
	}

	@Column(name = "CustomCreditLine", length = 200)
	public String getCustomCreditLine() {
		return this.customCreditLine;
	}

	public void setCustomCreditLine(String customCreditLine) {
		this.customCreditLine = customCreditLine;
	}

	@Column(name = "ManualArchiveCollection", length = 50)
	public String getManualArchiveCollection() {
		return this.manualArchiveCollection;
	}

	public void setManualArchiveCollection(String manualArchiveCollection) {
		this.manualArchiveCollection = manualArchiveCollection;
	}

	@Column(name = "AutomatedArchiveCollections", length = 10)
	public String getAutomatedArchiveCollections() {
		return this.automatedArchiveCollections;
	}

	public void setAutomatedArchiveCollections(
			String automatedArchiveCollections) {
		this.automatedArchiveCollections = automatedArchiveCollections;
	}

	@Column(name = "Displaylocation", length = 200)
	public String getDisplaylocation() {
		return this.displaylocation;
	}

	public void setDisplaylocation(String displaylocation) {
		this.displaylocation = displaylocation;
	}

	@Column(name = "ContractID")
	public Integer getContractId() {
		return this.contractId;
	}

	public void setContractId(Integer contractId) {
		this.contractId = contractId;
	}

	@Column(name = "ContractName", length = 200)
	public String getContractName() {
		return this.contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}

	@Column(name = "ModelReleaseStatus")
	public Byte getModelReleaseStatus() {
		return this.modelReleaseStatus;
	}

	public void setModelReleaseStatus(Byte modelReleaseStatus) {
		this.modelReleaseStatus = modelReleaseStatus;
	}

	@Column(name = "PropertyReleaseStatus")
	public Byte getPropertyReleaseStatus() {
		return this.propertyReleaseStatus;
	}

	public void setPropertyReleaseStatus(Byte propertyReleaseStatus) {
		this.propertyReleaseStatus = propertyReleaseStatus;
	}

	@Column(name = "Representationrights")
	public Integer getRepresentationrights() {
		return this.representationrights;
	}

	public void setRepresentationrights(Integer representationrights) {
		this.representationrights = representationrights;
	}

	@Column(name = "ModelReleaseIds", length = 50)
	public String getModelReleaseIds() {
		return this.modelReleaseIds;
	}

	public void setModelReleaseIds(String modelReleaseIds) {
		this.modelReleaseIds = modelReleaseIds;
	}

	@Column(name = "PropertyReleaseIds", length = 50)
	public String getPropertyReleaseIds() {
		return this.propertyReleaseIds;
	}

	public void setPropertyReleaseIds(String propertyReleaseIds) {
		this.propertyReleaseIds = propertyReleaseIds;
	}

	@Column(name = "MediaRatingText", length = 10)
	public String getMediaRatingText() {
		return this.mediaRatingText;
	}

	public void setMediaRatingText(String mediaRatingText) {
		this.mediaRatingText = mediaRatingText;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateShot", length = 19)
	public Date getDateShot() {
		return this.dateShot;
	}

	public void setDateShot(Date dateShot) {
		this.dateShot = dateShot;
	}

	@Column(name = "DateShotApprox", length = 100)
	public String getDateShotApprox() {
		return this.dateShotApprox;
	}

	public void setDateShotApprox(String dateShotApprox) {
		this.dateShotApprox = dateShotApprox;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LeftShotDate", length = 19)
	public Date getLeftShotDate() {
		return this.leftShotDate;
	}

	public void setLeftShotDate(Date leftShotDate) {
		this.leftShotDate = leftShotDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RightShotDate", length = 19)
	public Date getRightShotDate() {
		return this.rightShotDate;
	}

	public void setRightShotDate(Date rightShotDate) {
		this.rightShotDate = rightShotDate;
	}

	@Column(name = "FineArtCopyrightStatus")
	public Integer getFineArtCopyrightStatus() {
		return this.fineArtCopyrightStatus;
	}

	public void setFineArtCopyrightStatus(Integer fineArtCopyrightStatus) {
		this.fineArtCopyrightStatus = fineArtCopyrightStatus;
	}

	@Column(name = "FineArtCreditLine", length = 100)
	public String getFineArtCreditLine() {
		return this.fineArtCreditLine;
	}

	public void setFineArtCreditLine(String fineArtCreditLine) {
		this.fineArtCreditLine = fineArtCreditLine;
	}

	@Column(name = "IsInMotionSet")
	public Boolean getIsInMotionSet() {
		return this.isInMotionSet;
	}

	public void setIsInMotionSet(Boolean isInMotionSet) {
		this.isInMotionSet = isInMotionSet;
	}

	@Column(name = "IsInRFCD")
	public Boolean getIsInRfcd() {
		return this.isInRfcd;
	}

	public void setIsInRfcd(Boolean isInRfcd) {
		this.isInRfcd = isInRfcd;
	}

	@Column(name = "IsInMotionGroup")
	public Boolean getIsInMotionGroup() {
		return this.isInMotionGroup;
	}

	public void setIsInMotionGroup(Boolean isInMotionGroup) {
		this.isInMotionGroup = isInMotionGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateExpiration", length = 19)
	public Date getDateExpiration() {
		return this.dateExpiration;
	}

	public void setDateExpiration(Date dateExpiration) {
		this.dateExpiration = dateExpiration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePublished", length = 19)
	public Date getDatePublished() {
		return this.datePublished;
	}

	public void setDatePublished(Date datePublished) {
		this.datePublished = datePublished;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DomesticEmbargoDate", length = 19)
	public Date getDomesticEmbargoDate() {
		return this.domesticEmbargoDate;
	}

	public void setDomesticEmbargoDate(Date domesticEmbargoDate) {
		this.domesticEmbargoDate = domesticEmbargoDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InternationalEmbargoDate", length = 19)
	public Date getInternationalEmbargoDate() {
		return this.internationalEmbargoDate;
	}

	public void setInternationalEmbargoDate(Date internationalEmbargoDate) {
		this.internationalEmbargoDate = internationalEmbargoDate;
	}

	@Column(name = "Placement")
	public Integer getPlacement() {
		return this.placement;
	}

	public void setPlacement(Integer placement) {
		this.placement = placement;
	}

	@Column(name = "Pricing")
	public Integer getPricing() {
		return this.pricing;
	}

	public void setPricing(Integer pricing) {
		this.pricing = pricing;
	}

	@Column(name = "RightOfFirstSale")
	public Boolean getRightOfFirstSale() {
		return this.rightOfFirstSale;
	}

	public void setRightOfFirstSale(Boolean rightOfFirstSale) {
		this.rightOfFirstSale = rightOfFirstSale;
	}

	@Column(name = "OutlineSessionUID", length = 50)
	public String getOutlineSessionUid() {
		return this.outlineSessionUid;
	}

	public void setOutlineSessionUid(String outlineSessionUid) {
		this.outlineSessionUid = outlineSessionUid;
	}

	@Column(name = "IsOutline")
	public Boolean getIsOutline() {
		return this.isOutline;
	}

	public void setIsOutline(Boolean isOutline) {
		this.isOutline = isOutline;
	}

	@Column(name = "OutlineMagazineName", length = 1000)
	public String getOutlineMagazineName() {
		return this.outlineMagazineName;
	}

	public void setOutlineMagazineName(String outlineMagazineName) {
		this.outlineMagazineName = outlineMagazineName;
	}

	@Column(name = "MarketingCollectionID")
	public Integer getMarketingCollectionId() {
		return this.marketingCollectionId;
	}

	public void setMarketingCollectionId(Integer marketingCollectionId) {
		this.marketingCollectionId = marketingCollectionId;
	}

	@Column(name = "CollectionID")
	public Integer getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(Integer collectionId) {
		this.collectionId = collectionId;
	}

	@Column(name = "CollectionTier", length = 30)
	public String getCollectionTier() {
		return this.collectionTier;
	}

	public void setCollectionTier(String collectionTier) {
		this.collectionTier = collectionTier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChangedAt", length = 19)
	public Date getChangedAt() {
		return this.changedAt;
	}

	public void setChangedAt(Date changedAt) {
		this.changedAt = changedAt;
	}

	@Column(name = "KeyEnglish", length = 16777215)
	public String getKeyEnglish() {
		return this.keyEnglish;
	}

	public void setKeyEnglish(String keyEnglish) {
		this.keyEnglish = keyEnglish;
	}

	@Column(name = "KeyChinese", length = 16777215)
	public String getKeyChinese() {
		return this.keyChinese;
	}

	public void setKeyChinese(String keyChinese) {
		this.keyChinese = keyChinese;
	}

	@Column(name = "TermsSpecial", length = 16777215)
	public String getTermsSpecial() {
		return this.termsSpecial;
	}

	public void setTermsSpecial(String termsSpecial) {
		this.termsSpecial = termsSpecial;
	}

	@Column(name = "RestrictionIds", length = 100)
	public String getRestrictionIds() {
		return this.restrictionIds;
	}

	public void setRestrictionIds(String restrictionIds) {
		this.restrictionIds = restrictionIds;
	}

	@Column(name = "ContentWarningIds", length = 100)
	public String getContentWarningIds() {
		return this.contentWarningIds;
	}

	public void setContentWarningIds(String contentWarningIds) {
		this.contentWarningIds = contentWarningIds;
	}

	@Column(name = "MaxSizeCode")
	public Integer getMaxSizeCode() {
		return this.maxSizeCode;
	}

	public void setMaxSizeCode(Integer maxSizeCode) {
		this.maxSizeCode = maxSizeCode;
	}

	@Column(name = "Selector")
	public Integer getSelector() {
		return this.selector;
	}

	public void setSelector(Integer selector) {
		this.selector = selector;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SelectedDate", length = 19)
	public Date getSelectedDate() {
		return this.selectedDate;
	}

	public void setSelectedDate(Date selectedDate) {
		this.selectedDate = selectedDate;
	}

	@Column(name = "LastEditor")
	public Integer getLastEditor() {
		return this.lastEditor;
	}

	public void setLastEditor(Integer lastEditor) {
		this.lastEditor = lastEditor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InputDate", length = 19)
	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	@Column(name = "SelectionStatus")
	public Integer getSelectionStatus() {
		return this.selectionStatus;
	}

	public void setSelectionStatus(Integer selectionStatus) {
		this.selectionStatus = selectionStatus;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "SearchableInternal")
	public Boolean getSearchableInternal() {
		return this.searchableInternal;
	}

	public void setSearchableInternal(Boolean searchableInternal) {
		this.searchableInternal = searchableInternal;
	}

	@Column(name = "SearchableExternal")
	public Boolean getSearchableExternal() {
		return this.searchableExternal;
	}

	public void setSearchableExternal(Boolean searchableExternal) {
		this.searchableExternal = searchableExternal;
	}

	@Column(name = "Renderings", length = 1000)
	public String getRenderings() {
		return this.renderings;
	}

	public void setRenderings(String renderings) {
		this.renderings = renderings;
	}

	@Column(name = "ColorAppearance", length = 100)
	public String getColorAppearance() {
		return this.colorAppearance;
	}

	public void setColorAppearance(String colorAppearance) {
		this.colorAppearance = colorAppearance;
	}

	@Column(name = "OriginalMediaFormat", length = 20)
	public String getOriginalMediaFormat() {
		return this.originalMediaFormat;
	}

	public void setOriginalMediaFormat(String originalMediaFormat) {
		this.originalMediaFormat = originalMediaFormat;
	}

	@Column(name = "ProviderID")
	public Integer getProviderId() {
		return this.providerId;
	}

	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	@Column(name = "OriginalFilename", length = 100)
	public String getOriginalFilename() {
		return this.originalFilename;
	}

	public void setOriginalFilename(String originalFilename) {
		this.originalFilename = originalFilename;
	}

	@Column(name = "IPTC", length = 16777215)
	public String getIptc() {
		return this.iptc;
	}

	public void setIptc(String iptc) {
		this.iptc = iptc;
	}

	@Column(name = "SalesData", length = 50)
	public String getSalesData() {
		return this.salesData;
	}

	public void setSalesData(String salesData) {
		this.salesData = salesData;
	}

	@Column(name = "Remark", length = 50)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "AspectRatio", length = 10)
	public String getAspectRatio() {
		return this.aspectRatio;
	}

	public void setAspectRatio(String aspectRatio) {
		this.aspectRatio = aspectRatio;
	}

	@Column(name = "Orientation", length = 100)
	public String getOrientation() {
		return this.orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	@Column(name = "orgi_title", length = 1000)
	public String getOrgiTitle() {
		return this.orgiTitle;
	}

	public void setOrgiTitle(String orgiTitle) {
		this.orgiTitle = orgiTitle;
	}

	@Column(name = "orgi_MediaRatingText")
	public Integer getOrgiMediaRatingText() {
		return this.orgiMediaRatingText;
	}

	public void setOrgiMediaRatingText(Integer orgiMediaRatingText) {
		this.orgiMediaRatingText = orgiMediaRatingText;
	}

	@Column(name = "SourcePreFlvPath", length = 1000)
	public String getSourcePreFlvPath() {
		return this.sourcePreFlvPath;
	}

	public void setSourcePreFlvPath(String sourcePreFlvPath) {
		this.sourcePreFlvPath = sourcePreFlvPath;
	}

	@Column(name = "SourcePreMp4Path", length = 1000)
	public String getSourcePreMp4path() {
		return this.sourcePreMp4path;
	}

	public void setSourcePreMp4path(String sourcePreMp4path) {
		this.sourcePreMp4path = sourcePreMp4path;
	}

	@Column(name = "SourceDetMp4Path", length = 1000)
	public String getSourceDetMp4path() {
		return this.sourceDetMp4path;
	}

	public void setSourceDetMp4path(String sourceDetMp4path) {
		this.sourceDetMp4path = sourceDetMp4path;
	}
	
	@Column(name = "OnlineType")
	public Integer getOnlineType() {
		return this.onlineType;
	}

	public void setOnlineType(Integer onlineType) {
		this.onlineType = onlineType;
	}

}
